# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
 
        deployment: production  
        script: # Modify the commands below to build your repository.
          - cd functions && npm install && cd ..
          - npm run build
          - cp -Rf build/* ./public/
          - cp -Rf ./images ./public
          - cp -Rf ./fonts  ./public
          - pipe: atlassian/firebase-deploy:0.3.4
            variables:
              FIREBASE_TOKEN: $FIREBASE_TOKEN
              PROJECT_ID: $PROJECT_ID
              DEBUG: 'true'

